# Permalinks
permalink:        pretty

exclude: ['src', 'scripts', 'assets', 'node_modules', 'bower_components', 'coverage','examples']
version: 'v0.5.0'
downloadLink: 'https://github.com/BowlingX/marklib/archive/v.0.5.0.zip'